module.exports = {
    " ": "  ",
    "0": ":zero:",
    "1": ":one:",
    "2": ":two:",
    "3": ":three:",
    "4": ":four:",
    "5": ":five:",
    "6": ":six:",
    "7": ":seven:",
    "8": ":eight:",
    "9": ":nine:",
    "!": ":exclamation:",
    "?": ":question:",
    "#": ":hash:",
    "*": ":asterisk:",
    "+": ":heavy_plus_sign:",
    "-": ":heavy_minus_sign:",
    "$": ":heavy_dollar_sign:",
    ">": ":arrow_forward:",
    "<": ":arrow_backward:",
    "||": ":pause_button:"
};